import { useState, type FormEvent } from 'react';
import { login, signup } from '../services/auth';

export function AuthPage({ onAuthenticated, onBack }: { onAuthenticated: () => void; onBack: () => void }) {
  const [mode, setMode] = useState<'login' | 'signup'>('login');
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setLoading(true); try { await (mode === 'login' ? login({ email, password }) : signup({ name, email, password })); onAuthenticated(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível continuar agora.'); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-paper px-5 py-12 flex items-center justify-center"><section className="w-full max-w-md rounded-[24px] bg-brand-white p-8 shadow-[0_20px_50px_-20px_rgba(24,38,66,0.25)]"><button onClick={onBack} className="border-0 bg-transparent p-0 text-sm font-bold text-brand-blue cursor-pointer">← Voltar ao questionário</button><div className="mt-5 font-serif font-black text-[28px]">Trampol<span className="text-brand-red">i</span>m</div><h1 className="mt-5 text-[26px]">Veja seus resultados</h1><p className="mt-2 text-[#5a6480]">Entre ou crie sua conta para acessar cursos e vagas recomendados.</p><div className="mt-6 flex rounded-full bg-paper p-1"><button onClick={() => { setMode('login'); setError(''); }} className={`flex-1 rounded-full py-2 text-sm font-bold cursor-pointer border-0 ${mode === 'login' ? 'bg-ink text-brand-white' : 'bg-transparent text-ink'}`}>Entrar</button><button onClick={() => { setMode('signup'); setError(''); }} className={`flex-1 rounded-full py-2 text-sm font-bold cursor-pointer border-0 ${mode === 'signup' ? 'bg-ink text-brand-white' : 'bg-transparent text-ink'}`}>Criar conta</button></div><form className="mt-6 space-y-4" onSubmit={submit}>{mode === 'signup' && <label className="block text-sm font-bold">Nome<input required value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-xl border border-[#e7e0d0] bg-paper p-3 font-normal" /></label>}<label className="block text-sm font-bold">E-mail<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-xl border border-[#e7e0d0] bg-paper p-3 font-normal" /></label><label className="block text-sm font-bold">Senha<input type="password" required minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 w-full rounded-xl border border-[#e7e0d0] bg-paper p-3 font-normal" /></label>{error && <p role="alert" className="rounded-xl bg-[#fbe7e8] p-3 text-sm text-brand-red">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-ink p-3 font-extrabold text-brand-white cursor-pointer disabled:cursor-wait disabled:opacity-60">{loading ? 'Aguarde...' : mode === 'login' ? 'Entrar e ver resultados' : 'Criar conta e ver resultados'}</button></form></section></main>;
}
